### PR TITLE
Fix Role Binding for Custom Namespace

### LINKED ISSUE #147: Fix squash deploy squash --squash-namespace option
At now, the squash pod created by `squash deploy squash` with `--squash-namespace <custom namespace>`  fails excepts for `<custom namespace> == "squash-debugger"`.

The error message when I tried to deploy squash in namespace `tmp`:
```bash
time="2019-03-19T03:22:22Z" level=error msg=RunDebugBridge err="creating base DebugAttachment resource client: failed to register crd: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:tmp:squash\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope"
```

### PR DESCRIPTION
**Pull request by sanha**
**Major changes:**
- Fix the role binding to use the configured namespace instead of the default one.

closes #147.

### CODE REVIEW

**Comment by hgword** [comment]
👍

**Comment by yuval-k** [comment]
ci wasnt updating from some reason - i fixed it manually and its running now.

**Pull request merged**
