### PR TITLE
Adding namespace support for the extension

### LINKED ISSUE #181: Please add namespace support for the vscode extension
Squash vscode extension is not working. Please find below the version
* Environment:
```
k8s version - 1.12.7
vscode version - 1.33.1
Squash vscode extension version - 0.5.9
OS - macOS High Sierra
```
* Expected output: 
When I click `Squash - debug pod` the list of all pods should show up in the vscode UI
image
* Actual output: 
Instead of getting list of pods from the vscode UI as a list I am getting the json list of the pods in the vscode notification
image (1)
Please find the vscode logs for more details
Screen Shot 2019-04-23 at 5 46 54 PM
Please note that squashcli is working fine for me from terminal. Only the vscode extension is not working for me.

### PR DESCRIPTION
**Pull request by arindam-bandyopadhyay**
BOT NOTES:
resolves #181

### CODE REVIEW

**Comment by arindam-bandyopadhyay** [comment]
I tested it locally and it's working fine

**Comment by mitchdraft** [comment]
looks good, thanks for fixing this @arindam-bandyopadhyay !

**Pull request merged**
